# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 11:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPAccessLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CPAccessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='top', max_length=10)),
                ('source', models.CharField(default='Any', max_length=10)),
                ('destination', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('service', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('action', models.CharField(default='accept', max_length=10)),
                ('track', models.CharField(default='log', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CPFirewall',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gw_name', models.CharField(max_length=40)),
                ('management_url', models.CharField(max_length=256)),
                ('package_name', models.CharField(max_length=60)),
                ('layer_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CPGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('members', models.CharField(max_length=256)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cp.CPFirewall')),
            ],
        ),
        migrations.CreateModel(
            name='CPHost',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('ip_address', models.CharField(max_length=60)),
                ('access_rule', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='access_rule', to='cp.CPFirewall')),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='cp.CPFirewall')),
            ],
        ),
        migrations.CreateModel(
            name='CPNetwork',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('subnet', models.CharField(max_length=60)),
                ('subnet_mask', models.CharField(max_length=60)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='cp.CPFirewall')),
            ],
        ),
        migrations.CreateModel(
            name='CPPolicy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('fw', models.BooleanField(default=True)),
                ('anti_bot', models.BooleanField(default=True)),
                ('anti_virus', models.BooleanField(default=True)),
                ('application_control', models.BooleanField(default=False)),
                ('content_awareness', models.BooleanField(default=False)),
                ('ips', models.BooleanField(default=True)),
                ('threat_emulation', models.BooleanField(default=False)),
                ('url_filtering', models.BooleanField(default=False)),
                ('vpn', models.BooleanField(default=False)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blades', to='cp.CPFirewall')),
            ],
        ),
        migrations.CreateModel(
            name='CPSecurityPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CPService',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('port', models.CharField(max_length=10)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='cp.CPFirewall')),
            ],
        ),
        migrations.CreateModel(
            name='CPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_user', models.CharField(default='admin', max_length=20)),
                ('management_password', models.CharField(default='admin123', max_length=20)),
                ('firewall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cp.CPFirewall')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cpaccessrule',
            name='firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='cp.CPFirewall'),
        ),
        migrations.AddField(
            model_name='cpaccesslayer',
            name='firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_layers', to='cp.CPFirewall'),
        ),
    ]
