# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('cards', jsonfield.fields.JSONField()),
                ('deployed', models.BooleanField(default=False)),
                ('build_uuid', models.TextField(default='notSet')),
                ('build_prog', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
